
stages:
  - build
  - deploy



variables:
  AWS_DEFAULT_REGION: us-east-2         # The region of our S3 bucket
  BUCKET_NAME: zach-hugo-test-bucket    # Your bucket name

# ---- Build Stage ------
buildHugo: 
  stage: build
  script:
    - hugo -t $HUGO_THEME -v --baseURL="https://blog.oxalide.io/"

deployS3:
  stage: deploy
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./ s3://$BUCKET_NAME/ --recursive --exclude "*" --include "*.html"

